name: Append Commit Message to Markdown Files

on:
  push:
    branches:
      - changelog  # Change to your target branch if needed

jobs:
  append-commit-message:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history so that git log works correctly

      # Step 2: Append commit message to each modified .md file
      - name: Append commit message to modified Markdown files
        run: |
          # Get the current commit SHA from the environment variable
          COMMIT_SHA="${GITHUB_SHA}"
          echo "Processing commit: ${COMMIT_SHA}"
          
          # List files modified in this commit and filter for Markdown files.
          # Note: In a push with multiple commits you may need to adjust this.
          MD_FILES=$(git diff-tree --no-commit-id --name-only -r ${COMMIT_SHA} | grep -E '\.md$' || true)
          echo "Modified Markdown files: ${MD_FILES}"
          
          # Exit if no Markdown files were modified.
          if [ -z "$MD_FILES" ]; then
            echo "No Markdown files modified. Exiting."
            exit 0
          fi
          
          # Retrieve the commit message
          COMMIT_MSG=$(git log -1 --pretty=%B ${COMMIT_SHA})
          echo "Commit message:"
          echo "$COMMIT_MSG"
          
          # For each Markdown file, append a header and the commit message at the end.
          for file in $MD_FILES; do
            echo "" >> "$file"
            echo "## Commit Message" >> "$file"
            echo "$COMMIT_MSG" >> "$file"
            echo "Appended commit message to $file"
          done

      # Step 3 (Optional): Commit and push the changes back to the repository.
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          # Commit only if there are changes; otherwise, the commit command will fail.
          git commit -m "Append commit message to modified Markdown files" || echo "No changes to commit."
          git push origin HEAD:${{ github.ref }}
